services:
  app:
    build:
      context: .
      args:
        - AWS_REGION=${AWS_REGION}
    container_name: app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://labelDb:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:9.0.1
    container_name: labelDb
    ports:
      - 3307:3306
    restart: always
    volumes:
      - myvolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin -u root -p ${DB_ROOT_PASSWORD} ping -h localhost"]
      timeout: 20s
      retries: 10
volumes:
  myvolume: